import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "이성연과 김한은의 결혼식에 초대합니다",
  description: "Generated by Joshua Jonghan Kim",
  ogImage: '/images/thumbnail.png',
  ogImageWidth: '1200',
  ogImageHeight: '630',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
